public struct AVKey {
    static let values: [String: String] = [
        "version": "0.9.0",
        "absolute": "absolute",
        "afterRedraw": "afterRedraw",
        "beforeRedraw": "beforeRedraw",
        "began": "began",
        "cancelled": "cancelled",
        "changed": "changed",
        "clampToGround": "clampToGround",
        "earthRadius": "6371e3", // Deprecated, but included
        "east": "east",
        "ended": "ended",
        "failed": "failed",
        "filterLinear": "filter_linear",
        "filterNearest": "filter_nearest",
        "greatCircle": "greatCircle",
        "linear": "linear",
        "multiPoint": "multiPoint",
        "north": "north",
        "nullShape": "null",
        "offsetFraction": "fraction",
        "offsetInsetPixels": "insetPixels",
        "offsetPixels": "pixels",
        "point": "point",
        "polyline": "polyline",
        "polygon": "polygon",
        "possible": "possible",
        "recognized": "recognized",
        "redrawEventType": "WorldWindRedraw",
        "relativeToGlobe": "relativeToGlobe",
        "relativeToGround": "relativeToGround",
        "relativeToScreen": "relativeToScreen",
        "rhumbLine": "rhumbLine",
        "south": "south",
        "west": "west",
        "wgs84SemiMajorAxis": "6378137.0",
        "wgs84InverseFlattening": "298.257223563"
    ]
}
